/**
 * Onboarding Steps Definition
 * Defines all tutorial steps with tooltips, targets, and sequences
 */

import type { OnboardingStep } from '@/types/onboarding'

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: 'welcome',
    order: 0,
    title: 'Welcome to AI Assistant',
    description: 'Your privacy-first local AI companion that runs entirely in your browser.',
    icon: '🎉',
    highlighted: false,
    tooltip: {
      title: 'Welcome to AI Assistant',
      description:
        'This extension brings powerful AI capabilities directly to your browser. Everything runs locally on your device—no data leaves your computer.',
      position: 'center',
      action: 'Next',
    },
  },
  {
    id: 'chat-input',
    order: 1,
    title: 'Start Chatting',
    description: 'Type your messages in the input field below to chat with the AI.',
    icon: '💬',
    targetId: 'message-input-textarea',
    highlighted: true,
    tooltip: {
      title: 'Write Your Message',
      description: 'Click here to type your questions or requests. You can ask anything from general knowledge to coding help.',
      position: 'top',
      action: 'Got it',
    },
  },
  {
    id: 'send-button',
    order: 2,
    title: 'Send Messages',
    description: 'Click the send button to submit your message to the AI.',
    icon: '📤',
    targetId: 'send-button',
    highlighted: true,
    tooltip: {
      title: 'Send Your Message',
      description: 'Press this button (or use Ctrl+Enter) to send your message to the AI assistant.',
      position: 'left',
      action: 'Next',
    },
  },
  {
    id: 'tools',
    order: 3,
    title: 'Enable AI Tools',
    description: 'Give the AI access to tools like weather, web search, and memory search for enhanced capabilities.',
    icon: '⚙️',
    targetId: 'tools-button',
    highlighted: true,
    tooltip: {
      title: 'AI Tools',
      description: 'Click the settings icon to enable/disable AI tools like Weather, Web Search, and Memory Search. These extend what the AI can do.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'ai-provider',
    order: 4,
    title: 'Choose Your AI Model',
    description: 'Select different AI models based on your preference and device capabilities.',
    icon: '🤖',
    targetId: 'provider-selector',
    highlighted: true,
    tooltip: {
      title: 'AI Model Selection',
      description: 'Choose between Built-in AI (fastest), WebLLM, or Transformers.js. Built-in AI is recommended for the best experience.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'image-upload',
    order: 5,
    title: 'Attach Images',
    description: 'Upload images for the AI to analyze (Built-in AI only). Perfect for screenshots and visual questions.',
    icon: '🖼️',
    targetId: 'image-upload-button',
    highlighted: true,
    tooltip: {
      title: 'Image Analysis',
      description: 'Click here to attach an image. The AI can analyze screenshots, diagrams, and photos. Available with Built-in AI.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'voice-input',
    order: 6,
    title: 'Voice Input',
    description: 'Click the microphone button to send voice messages. Your speech will be transcribed to text.',
    icon: '🎤',
    targetId: 'voice-button',
    highlighted: true,
    tooltip: {
      title: 'Speak Your Message',
      description: 'Click the microphone icon to use speech-to-text. Just speak and the AI will transcribe it. Perfect for hands-free interaction.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'memory-panel',
    order: 7,
    title: 'Save to Memory',
    description: 'Save important messages and knowledge with semantic search capability for future reference.',
    icon: '🧠',
    targetId: 'memory-panel-button',
    highlighted: true,
    tooltip: {
      title: 'Semantic Memory',
      description: 'Save important conversations and knowledge. Search them later by meaning, not just keywords. Your personal AI knowledge base.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'bookmarks',
    order: 8,
    title: 'Quick Bookmarks',
    description: 'Quickly save messages as bookmarks for fast access later. No complexity, just quick saves.',
    icon: '🔖',
    targetId: 'bookmarks-panel-button',
    highlighted: true,
    tooltip: {
      title: 'Quick Access',
      description: 'Bookmark important messages for quick access. Click the bookmark icon on any message to save it instantly.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'context-menu',
    order: 9,
    title: 'Right-Click Features',
    description: 'Right-click on any web page to summarize content, save pages, rewrite text, and more.',
    icon: '🖱️',
    highlighted: false,
    tooltip: {
      title: 'Context Menu Powers',
      description: 'Right-click on web pages to summarize them, rewrite selected text in different tones, or save page summaries to your memory.',
      position: 'center',
      action: 'Next',
    },
  },
  {
    id: 'settings',
    order: 10,
    title: 'Settings & Theme',
    description: 'Customize the theme, reset chats, and manage your preferences in the settings menu.',
    icon: '⚙️',
    targetId: 'settings-button',
    highlighted: true,
    tooltip: {
      title: 'Settings',
      description: 'Access your settings to change themes (Light/Dark/System), reset chats, and manage preferences.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'multi-chat',
    order: 11,
    title: 'Multiple Chats',
    description: 'Create and manage multiple conversation threads. Each chat maintains its own history.',
    icon: '💭',
    targetId: 'chat-sidebar-button',
    highlighted: true,
    tooltip: {
      title: 'Chat Organization',
      description: 'Create multiple independent chat sessions for different topics. All conversations are saved automatically.',
      position: 'bottom',
      action: 'Next',
    },
  },
  {
    id: 'ready',
    order: 12,
    title: 'You\'re All Set!',
    description: 'You\'re ready to start using AI Assistant. Happy chatting!',
    icon: '🚀',
    highlighted: false,
    tooltip: {
      title: 'Let\'s Get Started',
      description: 'You now know all the basics. Feel free to explore more features as you use the app. Enjoy your AI assistant!',
      position: 'center',
      action: 'Complete',
    },
  },
]
